### ISSUE TITLE
.npz trained file

### ISSUE THREAD

**Issue by jamessteve** [VisualComputingInstitute/BiternionNets-ROS#3]
Hi, 

Is it possible for you to provide me one of the .npz trained files (either for head or body models) so I can test the orientation prediction on my data without training the model? 

Thank you.

Regards.

**Comment by lucasb-eyer** [comment]
Hi,

I'm afraid I can't yet, because all those I have have been trained on very privacy-sensitive data. I plan to release a .npz file in the future, but can't promise anything.

But this issue reminds me that I should write a tutorial on how to train your own, all the code for that is available. Would that be useful to you?

**Comment by jamessteve** [comment]
Hello, 

Thank you for your reply. 

I understand that you cannot release it because of the privacy issues. A tutorial would be great and helpful and it would also be great if you have any available labelled data for the training process. 

Regards.

**Comment by lucasb-eyer** [comment]
Ok, we'll work on a tutorial. About labelled data, we may be able to publish a little for example purposes, but definitely not enough to train a stable model (due to the same privacy issues). It's really unfortunate.

I'll keep this issue open until we get a tutorial ready! It may take a little while though.

**Comment by lucasb-eyer** [comment]
We've added a description of the training procedure to the README. It's actually pretty simple once one has done it, but I understand it might seem daunting at first due to the dependency on a detector/tracker, so it's more of a "whole system" kind of thing than a "small part" kind of thing.

Hope this helps!
